### ISSUE TITLE
Sea of Thieves Cursor Visible

### ISSUE THREAD

**Issue by Jayden876212old** [Plagman/gamescope#733] opened 2023-01-04 17:44 UTC
Due to a recent commit in the past couple months, the cursor in Sea of Thieves remains visible even in first person. This behaviour was not present before. The cursor should be invisible in first person and visible in menus. Yes, the cursor moves around when I move my camera around. See the picture below for an example of this behaviour.
![image](https://user-images.githubusercontent.com/110114652/210616775-5e4d4375-8f9e-4a71-8909-c28a27545da8.png)
I am using an RX 6600XT on Arch Linux with everything up to date as of now and I am using gamescope on hyprland. I playing the game through steam with Proton GE and gamemode and have tested without gamescope and it works fine.

**Comment by tdljayden** [comment] 2023-01-05 18:08
I will test more when I have the chance. It was wrong of me to assume the issue was with a commit to gamescope and not an update to some other package on my system.

**Comment by tdljayden** [comment] 2023-01-05 19:41
I downgraded to `libx11 1.8.2-2` from the archive and it appears to be working now. I did try `lib32x11` from my personal pacman cache and that didn't have any effect so if anybody is following the steps here and is as mistake-prone as I am, make sure you are downgrading the right package.

So the issue is an update to `libx11` then.

**Comment by KagoraTheGrindcoreAddict** [comment] 2023-01-09 12:04
Appears to be fixed with `libx11 1.8.3-5` and `gamescope-git 3.11.51.r85.gbb523af-1 (Build Date: Sat 07 Jan 2023 08:13:15 AM)`

**Comment by tdljayden** [comment] 2023-01-09 15:32
Will test when I get the chance. If it works I'll close the issue.

**Comment by tdljayden** [comment] 2023-01-11 19:04
Yeah it works with the latest update. Thanks for the help.

**Closed as completed by tdljayden** 2023-01-11 19:04 UTC
