### ISSUE TITLE
Missing mouse acceleration inside gamescope.

### ISSUE THREAD

**Issue by Vinjul1704** [Plagman/gamescope#282] opened 2021-10-01 22:21 UTC
Mouse acceleration is missing within gamescope. This can mess with what many people are used to and is especially annoying when using input devices that benefit more from mouse accel than raw or flat mouse movement, such as trackballs.

Is this by design? If not, is there any plan to implement using default OS mouse settings, including acceleration?

Thanks!

**Comment by emersion** [comment] 2021-10-02 13:17
Duplicate of https://github.com/Plagman/gamescope/issues/196

**Closed by emersion** 2021-10-02 13:17 UTC
