### ISSUE TITLE
Is there a way to set,that the name and icon of the program get showed instead of the title "gamescope"

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#139] opened 2020-12-06 23:23 UTC
I want that it shows the name and icon of the program instead of "gamescope" and that [standard icon](https://i.imgur.com/EnuYEjA.png).

**Comment by emersion** [comment] 2020-12-06 23:26
Duplicate of https://github.com/Plagman/gamescope/issues/10

**Closed by emersion** 2020-12-06 23:26 UTC
