### ISSUE TITLE
[Feature Request] Being able to enable it globally

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#152] opened 2021-01-18 08:10 UTC
I wanna use it for every program and game,so it would be cool to enable it globally with something like an env var.
I don't know if it works if you just do `gamescope --` in .profile.

**Comment by Valmar33** [comment] 2021-01-18 08:22
You really wouldn't want to use this for every program.

It doesn't work quite how you think it does.

**Comment by emersion** [comment] 2021-01-18 09:34
Duplicate of https://github.com/Plagman/gamescope/issues/133

**Closed by emersion** 2021-01-18 09:34 UTC

**Comment by Toadfield** [comment] 2021-01-25 19:12
@emersion 
Oh,I duplicated my own post.
I forgot that I already asked that.

**Comment by Toadfield** [comment] 2021-01-25 19:15
@Valmar33 
I mean I could disable it if there would be an env var,by "env var="" " I think.
And does it really cause so much programs?
Cause I just wanna use it on all my games without the need to apply it manually.
