### ISSUE TITLE
gamescope results in distorted and disfigured visuals

### ISSUE THREAD

**Issue by thisismyaccount1996** [Plagman/gamescope#480] opened 2022-04-30 12:01 UTC
I'm trying to play the  2001 classic [The Mystery of the Druids](https://en.wikipedia.org/wiki/The_Mystery_of_the_Druids).  The game works very well with wine (with emulated desktop) but the resolution is too small for modern screens.  I tried to use gamescope to scale the game, but this resulted in heavily distorted and disfigured visuals.  See screenshots of original and with gamescope.

**with gamescope:**
![Screenshot_2022-04-30_13-47-57](https://user-images.githubusercontent.com/84734374/166104408-4f41f533-c455-47de-af74-0235b8d719a3.png)
**original**
![Screenshot_2022-04-30_13-49-06](https://user-images.githubusercontent.com/84734374/166104409-e106e52b-9022-4bd2-9298-5f2efd97045d.png)

I'm running:
`wine explorer /desktop=name edd.exe` vs `gamescope wine explorer /desktop=name edd.exe`  (also tried with -n, got same results).  Game doesn't run without emulated desktop.

Some diagnostic info below:

**Terminal output:**
```
$ gamescope wine explorer /desktop=name edd.exe 
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
[2022-04-30 13:45:41.733] [MANGOHUD] [info] [config.cpp:114] skipping config: '/usr/bin/MangoHud.conf' [ not found ]
[2022-04-30 13:45:41.733] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/z/.config/MangoHud/gamescope.conf' [ not found ]
[2022-04-30 13:45:41.733] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/z/.config/MangoHud/MangoHud.conf'
vulkan: selecting physical device 'Intel(R) Iris(R) Plus Graphics (ICL GT2)'
vulkan: physical device supports DRM format modifiers
[2022-04-30 13:45:41.811] [MANGOHUD] [error] [loader_nvml.cpp:42] Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
[2022-04-30 13:45:41.811] [MANGOHUD] [error] [nvml.cpp:41] Failed to load NVML
[2022-04-30 13:45:41.818] [MANGOHUD] [error] [nvctrl.cpp:53] XNVCtrl didn't find the correct display
[2022-04-30 13:45:41.818] [MANGOHUD] [info] [overlay.cpp:678] Uploading is disabled (permit_upload = 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: [backend/headless/backend.c:82] Creating headless backend
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [xwayland/server.c:92] Starting Xwayland on :1
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86EmojiPicker
Errors from xkbcomp are not fatal to the X server
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x558b81652250 (res 0x558b81626a90)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 79
pipewire: renegociating stream params (size: 1280x720)
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x558b8221e770 (res 0x558b81649ae0)
0104:fixme:imm:ImeSetActiveContext (0x2604d8, 0): stub
0104:fixme:imm:ImmReleaseContext (00020042, 002604D8): stub
0114:fixme:imm:ImeSetActiveContext (0x47d950, 1): stub
0114:fixme:imm:ImmReleaseContext (0001007A, 0047D950): stub
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x558b81db5640 (res 0x558b8164f6d0)
0114:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
xwm: Unhandled NET_WM_STATE property change: _NET_WM_STATE_MAXIMIZED_VERT
xwm: Unhandled NET_WM_STATE property change: _NET_WM_STATE_MAXIMIZED_HORZ
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
0140:fixme:d3d:texture2d_blt Can't handle WINED3D_BLT_DO_NOT_WAIT flag.
0140:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
0114:fixme:ddraw:ddraw_surface1_Flip Ignoring flags 0x20.
```

**Diagnostic info:**

gamescope version 3.11.22

```
$ uname -a
Linux 5.17.1-3-MANJARO #1 SMP PREEMPT Thu Mar 31 12:27:24 UTC 2022 x86_64 GNU/Linux

$ inxi -G
Graphics:
  Device-1: Intel Iris Plus Graphics G7 driver: i915 v: kernel
  Device-2: Chicony Integrated Camera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.3 with: Xwayland v: 22.1.1 driver:
    X: loaded: intel gpu: i915 resolution: 1600x900~60Hz
  OpenGL: renderer: Mesa Intel Iris Plus Graphics (ICL GT2)
    v: 4.6 Mesa 21.3.8
```

**Comment by Samsagax** [comment] 2022-04-30 16:04
I think you are hit by #356

**Comment by Joshua-Ashton** [comment] 2022-05-05 23:44
Dupe of https://github.com/Plagman/gamescope/issues/356

**Closed by Joshua-Ashton** 2022-05-05 23:44 UTC
