### ISSUE TITLE
Figure out why we're not always 'flipping' in Xwayland

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#21] opened 2020-01-21 02:21 UTC
Dragon Dogma has Xwayland rendering in the gfx pipe. Why? It needs to go.

**Comment by Plagman** [comment] 2020-01-21 02:48
Looks like windowed makes it flip, fullscreen not. Possible related to resizing or reparenting. It really screws up frame cadence as well, as not flipping makes us get a single commit every vblank, not when apps actually commit.

**Comment by subdiff** [comment] 2020-01-27 13:57
I would have said that is more likely to not flip in windowed mode if you look at the restrictions:
* [Present check](https://gitlab.freedesktop.org/xorg/xserver/blob/master/present/present_wnmd.c#L244)
* [XWayland implementation](https://gitlab.freedesktop.org/xorg/xserver/blob/0839b0523a01067cb9c9b53ebdd9ce4c00f0eb12/hw/xwayland/xwayland-present.c#L419)

I would take a look at the fullscreen Pixmap size and it differs for some reason from the Window/Screen size.

**Comment by Oschowa** [comment] 2020-01-28 11:11
See my comments in this issue https://github.com/doitsujin/dxvk/issues/1358#issuecomment-576330701,
it seems to be indeed the screen <> window size mismatch which happens with this game that prevents flipping.

**Comment by Joshua-Ashton** [comment] 2020-03-11 17:48
This was fixed in DXVK as of https://github.com/doitsujin/dxvk/commit/14946c599f7450cda1c46efb3177d7b549873669

**Comment by Plagman** [comment] 2020-09-01 19:01
When runnning Sekiro in Fullscreen at a non-native res with all the latest stuff, we get a copy in XWayland still.

**Comment by Plagman** [comment] 2020-09-01 19:03
Very easy to notice if you don't have R600_DEBUG=nodcc, because output gets all corrupt at that point, presumably because the internal XWayland copy uses GL.

On embedded I only get a white screen when Sekiro is in fullscreen, which is peculiar.

**Comment by Plagman** [comment] 2020-09-01 22:22
White screen was https://github.com/Plagman/gamescope/issues/97.

**Comment by Plagman** [comment] 2020-09-02 01:41
OK so if Sekiro starts in fullscreen, it flips just fine, and the compositing cadence looks nice. If I switch to windowed, and then fullscreen, it both starts blitting inside of Xwayland, and we stop being able to flip game buffers directly to DRM, so it's a double-whammy of pain.

**Comment by subdiff** [comment] 2020-09-03 15:58
It sounds like that either an additional parent window is created by wlroots when being windowed (KWinFT does this too for decorations) or that the size is not correctly updated when going fullscreen by wlroots.

Adding debug lines around [here](https://gitlab.freedesktop.org/xorg/xserver/-/blob/727df0a74e75982f4352f0a3e574fcf6db3372f7/present/present_wnmd.c#L309-327) and [here](https://gitlab.freedesktop.org/xorg/xserver/-/blob/727df0a74e75982f4352f0a3e574fcf6db3372f7/hw/xwayland/xwayland-present.c#L411-412) should provide more information.

**Comment by subdiff** [comment] 2020-09-03 16:20
True, then the XWM part of gamescope might do some reparenting. In any case some `ErrorF` in above code parts of Xwayland might give more information.

**Comment by emersion** [comment] 2020-09-03 16:24
On my setup, this happens:

- Fullscreen with a 1280x720 resolution: flips
- Fullscreen with a different resolution: doesn't flip, hits the "Flip pixmap must have same dimensions as window" check
- Windowed, with any resolution: flips

Xwayland patch to debug whether we flips happen or not: https://paste.sr.ht/~emersion/a483dff801f7351102699971b8fecc644cbca913

**Comment by Plagman** [comment] 2020-09-10 05:40
There is no reparenting involved in steamcompmgr (the XWM part of gamescope).

**Comment by rbernon** [comment] 2020-09-10 08:28
Hi @emersion! I haven't really looked at it yet on Wine side but it would be helpful if you could get output logs with `WINEDEBUG=+x11drv,+win,+event` environment variable set for a good and for a bad fullscreen resolution (or a single log with both but it may be hard to tell when it's going bad, unless you can have the Xwayland messages interleaved).

**Comment by rbernon** [comment] 2020-09-14 15:38
So I started Sekiro within gamescope using `gamescope -w 1600 -h 900 -W 1600 -H 900 -- %command%`, and I can reproduce the flip error messages in Xwayland when I set the game graphics settings to fullscreen and a resolution different from 1600x900. 

I tracked down the issue to be Proton fshack, which scales the fullscreen output back to the default resolution of 1600x900, as actually intended, making the vulkan render pixmap to be 1600x900 although the window was indeed resized to another resolution. Disabling fshack altogether, for instance when gamescope is detected, solves the missing flips.

IIUC gamescope and fshack are both meant to solve the same issue, so it would make sense to stop using fshack if gamescope is detected, right?

**Comment by rbernon** [comment] 2020-09-14 15:40
FWIW it also seems that when switching back from windowed 1280x720 to fullscreen 1280x720 (with a desktop resolution of 1600x900), the issue does not happen. For some reason, fshack doesn't recreate its output pixmap in that case, not sure why.

**Comment by rbernon** [comment] 2020-09-14 17:42
[0001-winex11.drv-Disable-fshack-swapchain-when-gamescope-.txt](https://github.com/Plagman/gamescope/files/5219750/0001-winex11.drv-Disable-fshack-swapchain-when-gamescope-.txt)

This patch for Proton 5.0 fixes the missed flips in Xwayland for me, could you confirm and see if it fixes the rest too?

**Comment by emersion** [comment] 2020-10-23 10:25
I just tried out the latest commit of Proton, and I can confirm we're now flipping in fullscreen mode regardless of the resolution. Thanks!

**Closed by emersion** 2020-10-23 10:25 UTC
Labels: next
