### ISSUE TITLE
Use key binds from compositor/window manager

### ISSUE THREAD

**Issue by Jeselnik** [Plagman/gamescope#194] opened 2021-05-13 13:25 UTC
When running nested in sway with option `input "type:keyboard" xkb_options caps:swapescape` in config to swap ESC and Caps gamescope windows instead use the standard key mapping and ESC still activates the caps lock light. 

If this fix isn't out of scope it would be appreciated

**Comment by emersion** [comment] 2021-07-20 11:14
Closing as a duplicate of https://github.com/Plagman/gamescope/issues/203

**Closed by emersion** 2021-07-20 11:14 UTC
