### ISSUE TITLE
Default X11 cursor is used (Cross)

### ISSUE THREAD

**Issue by aqxa1** [Plagman/gamescope#121] opened 2020-11-03 00:54 UTC
Currently, the default X11 cursor (a cross) is used, which is kind of ugly. A very minor issue, but would be nice to fix once this rolls out to normal users.

**Comment by emersion** [comment] 2020-11-09 20:05
Ref https://github.com/swaywm/wlroots/blob/238d1c078fb03338e9f271d98f7bf6b1fc399285/xwayland/xwm.c#L1788

**Comment by Plagman** [comment] 2020-11-13 05:35
In the past we had an external program set a fancy ARGB cursor on the root window in the Big Picture steamcompmgr SteamOS session. It probably makes sense to keep it that way and let the cursor be up to the session, but in embedded mode we should probably just readback the cursor from the actual host desktop and mimic it. I'd say this is a dupe of https://github.com/Plagman/gamescope/issues/12.

**Comment by emersion** [comment] 2020-11-13 06:41
Makes sense.

**Closed by emersion** 2020-11-13 06:41 UTC
