### ISSUE TITLE
Wonky mouse inputs in embedded session

### ISSUE THREAD

**Issue by Joshua-Ashton** [Plagman/gamescope#238] opened 2021-08-21 00:29 UTC
When playing in embedded session mode, the mouse doesn't seem to get reset to the centre of the screen every frame, causing you to always look entirely up and spin or down and spin. This doesn't happen in nested.

An easy way to reproduce this is to play Half-Life 2 with a mouse and keyboard inside an embedded session.

**Comment by emersion** [comment] 2021-08-21 06:44
Duplicate of https://github.com/Plagman/gamescope/issues/19

**Closed by emersion** 2021-08-21 06:44 UTC

**Comment by Alexbay218** [comment] 2022-08-03 03:40
Tried this with planetside 2 and gamescope embedded seems to prevent the mouse from moving past the screen (making you only able to aim in like a 70 degree wide rectangle). Note this is with a bluetooth mouse (not the touchpad on steamdeck).

**Comment by Alexbay218** [comment] 2022-08-03 03:46
Also tested with non-bluetooth wireless mouse. Same issue on planetside 2. On MGSV TPP, mouse will spin like described
