### ISSUE TITLE
Gamescope defaults to QWERTY keyboard layout regardless of system wide layout

### ISSUE THREAD

**Issue by MGThePro** [Plagman/gamescope#237] opened 2021-08-18 13:51 UTC
I'm using plasma wayland as my regular desktop session with the de keyboard layout set, but regardless of that any application running inside gamescope defaults to some qwerty layout (I'm guessing the us layout?)

Can be tested with any xorg application that accepts keyboard input, even a text editor, for example `QT_QPA_PLATFORM=xcb gamescope -- kate`

**Comment by emersion** [comment] 2021-08-18 13:53
Duplicate of https://github.com/Plagman/gamescope/issues/203

**Closed by emersion** 2021-08-18 13:53 UTC
