### ISSUE TITLE
Fails to run on NVIDIA GBM KDE session

### ISSUE THREAD

**Issue by lionblaze55** [Plagman/gamescope#313] opened 2021-11-19 00:36 UTC
Fails to run on my KDE NVIDIA wayland GBM session with patched QT-5. Is this something supportable now that GBM backend is enabled on NVIDIA?

```
gamescope glxgears
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: selecting physical device 'NVIDIA GeForce GTX 1070'
vulkan: physical device does not support DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -7)
Failed to initialize Vulkan
```

**Comment by Joshua-Ashton** [comment] 2021-11-19 01:40
Nvidia needs to implement modifiers, not a bug.

**Comment by emersion** [comment] 2021-11-19 08:24
Duplicate of https://github.com/Plagman/gamescope/issues/151

**Closed by emersion** 2021-11-19 08:24 UTC
